[package]
name = "stateful"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_yaml = "0.9.34-deprecated"
reqwest = { version = "0.12.23", features = ["json", "stream"] }
